### PR TITLE
Control-Tower Changes - Migrating from AWS API polling integrations to Metrics Streaming

### PR DESCRIPTION
**Pull request by SuruchiSaboo**
Control-Tower Changes - Migrating from AWS API polling integrations to Metrics Streaming.

Existing integration uses API polling to fetch metrics from AWS accounts.
With this commit deployed, metrics will automatically stream to New Relic instead of API polling them.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by davmayd** [comment]
Hi @SuruchiSaboo. There are a couple issues with this pull request that need to be addressed before it can be tested and merged:

- While changes to code are submitted to the `main` branch of the repo, changes to the deployment guide are submitted to the `doc-edits` branch. This change was implemented more recently than the last update to this repo (it looks like it hasn't been updated in two years).

- The new template "MetricStreams_CloudFormation.yml" doesn't have a unique QSID in the description, causing our linting to fail and preventing us from running CI tests to ensure the code deploys successfully.

**Comment by anshrma** [comment]
> Hi @SuruchiSaboo. There are a couple issues with this pull request that need to be addressed before it can be tested and merged:
> 
> * While changes to code are submitted to the `main` branch of the repo, changes to the deployment guide are submitted to the `doc-edits` branch. This change was implemented more recently than the last update to this repo (it looks like it hasn't been updated in two years).
> * The new template "MetricStreams_CloudFormation.yml" doesn't have a unique QSID in the description, causing our linting to fail and preventing us from running CI tests to ensure the code deploys successfully.

Hi @davmayd - While @SuruchiSaboo changes the destination branch, can you please confirm what is the QSID that should be used for the new template ?

**Comment by davmayd** [comment]
> > Hi @SuruchiSaboo. There are a couple issues with this pull request that need to be addressed before it can be tested and merged:
> > 
> > * While changes to code are submitted to the `main` branch of the repo, changes to the deployment guide are submitted to the `doc-edits` branch. This change was implemented more recently than the last update to this repo (it looks like it hasn't been updated in two years).
> > * The new template "MetricStreams_CloudFormation.yml" doesn't have a unique QSID in the description, causing our linting to fail and preventing us from running CI tests to ensure the code deploys successfully.
> 
> Hi @davmayd - While @SuruchiSaboo changes the destination branch, can you please confirm what is the QSID that should be used for the new template ?

Hi @anshrma. Please append `(qs-1u8uthf5u)` to the template description. Rather than changing the destination branch, please create two separate pull requests: all `/docs` changes to the `doc-edits` branch and all other edits to the `main` branch.

**Comment by SuruchiSaboo** [comment]
> Hi @SuruchiSaboo. There are a couple issues with this pull request that need to be addressed before it can be tested and merged:
> 
> * While changes to code are submitted to the `main` branch of the repo, changes to the deployment guide are submitted to the `doc-edits` branch. This change was implemented more recently than the last update to this repo (it looks like it hasn't been updated in two years).
> * The new template "MetricStreams_CloudFormation.yml" doesn't have a unique QSID in the description, causing our linting to fail and preventing us from running CI tests to ensure the code deploys successfully.

**Comment by SuruchiSaboo** [comment]
I've appended the QSID to MetricStreams_CloudFormation.yml and removed all deployment guide changes from this commit.

I've also raised a separate PR in doc-edits branch for document changes.
https://github.com/aws-quickstart/quickstart-ct-newrelic-one/pull/32/files.

**Comment by davmayd** [comment]
do-e2e-tests

**Review by davmayd — APPROVED** [review]

**Pull request merged**
